@{
    RootModule = 'EdgePolicyModule.psm1'
    ModuleVersion = '1.0.0'
    GUID = '7e4b6e4a-1234-5678-9012-345678901234'
    Author = 'Your Name'
    CompanyName = 'Your Company'
    Copyright = '(c) 2025. All rights reserved.'
    Description = 'PowerShell module for managing Microsoft Edge policies'
    PowerShellVersion = '7.0'
    RequiredModules = @()
    FunctionsToExport = @(
        'New-EdgePolicyPath',
        'Set-EdgePolicy',
        'Remove-EdgePolicy',
        'Get-EdgePolicy',
        'Set-EdgePolicyAddressBarEditingEnabled',
        'Set-EdgePolicyAddressBarMicrosoftSearchInBingProviderEnabled',
        'Set-EdgePolicyDownloadDirectory',
        'Set-EdgePolicyDownloadRestrictions',
        'Set-EdgePolicyNewTabPageContentEnabled',
        'Set-EdgePolicyNewTabPageLocation',
        'Set-EdgePolicyNewTabPageManagedQuickLinks',
        'Set-EdgePolicySmartScreenEnabled',
        'Set-EdgePolicySmartScreenForTrustedDownloadsEnabled',
        'Set-EdgePolicySmartScreenAllowListDomains',
        'Set-EdgePolicyClearBrowsingDataOnExit',
        'Set-EdgePolicyClearCachedImagesAndFilesOnExit',
        'Set-EdgePolicyBlockThirdPartyCookies',
        'Set-EdgePolicyEfficiencyModeEnabled',
        'Set-EdgePolicyStartupBoostEnabled',
        'Set-EdgePolicyEfficiencyMode',
        'Set-EdgePolicyShowHomeButton',
        'Set-EdgePolicyFavoritesBarEnabled',
        'Set-EdgePolicyMouseGestureEnabled',
        'Set-EdgePolicyExtensionInstallAllowlist',
        'Set-EdgePolicyExtensionInstallBlocklist',
        'Set-EdgePolicyDefaultJavaScriptSetting',
        'Set-EdgePolicyDefaultCookiesSetting',
        'Set-EdgePolicyAuthSchemes',
        'Set-EdgePolicyBasicAuthOverHttpEnabled',
        'Set-EdgePolicyPDFReaderEnabled',
        'Set-EdgePolicyPDFReaderViewXFAAllowedFileHash',
        'Set-EdgePolicyCACertificateManagementAllowed',
        'Set-EdgePolicyCACertificates',
        'Set-EdgePolicyAutomaticProfileSwitchingSiteList',
        'Set-EdgePolicyDefaultSearchProviderName',
        'Set-EdgePolicyDefaultSearchProviderURL',
        'Set-EdgePolicyProxyMode',
        'Set-EdgePolicyProxyServer',
        'Set-EdgePolicyProxyPacUrl',
        'Set-EdgePolicyBlockExternalExtensions',
        'Set-EdgePolicyAllAuthSchemesAllowedForOrigins',
        'Set-EdgePolicyDelegateAuthSchemesAllowedForOrigins',
        'Set-EdgePolicyExtensionAllowedTypes',
        'Set-EdgePolicyExtensionInstallForcelist',
        'Set-EdgePolicyExtensionInstallBlocklistExceptions',
        'Set-EdgePolicyNetworkPredictionOptions',
        'Set-EdgePolicyNetworkServiceSandboxEnabled',
        'Set-EdgePolicyPasswordManagerEnabled',
        'Set-EdgePolicyScarewareBlockerProtectionEnabled',
        'Set-EdgePolicyScreenCaptureAllowed',
        'Set-EdgePolicyWebRtcLocalIpsAllowedUrls',
        'Set-EdgePolicyApplicationGuardContainerProxy',
        'Set-EdgePolicyPrivateNetworkRequestPolicy',
        'Set-EdgePolicySleepingTabsEnabled',
        'Set-EdgePolicySleepingTabsDelaySeconds',
        'Set-EdgePolicyEdgeManagementEnabled',
        'Set-EdgePolicyEdgeManagementEnrollmentToken',
        'Set-EdgePolicyDefaultBrowserSettingEnabled',
        'Set-EdgePolicyDefaultBrowserSettingsCampaignEnabled',
        'Set-EdgePolicyComponentUpdatesEnabled',
        'Set-EdgePolicyBrowserCodeIntegritySetting',
        'Set-EdgePolicyKioskAddressBarEditingEnabled',
        'Set-EdgePolicyKioskDeleteDownloadsOnExit',
        'Set-EdgePolicyEdgeDefaultProfileEnabled',
        'Set-EdgePolicyCastEnabled',
        'Set-EdgePolicyCastScreenEnabled',
        'Set-EdgePolicyImmersiveReaderEnabled',
        'Set-EdgePolicyImmersiveReaderAllowedDomains',
        'Set-EdgePolicyNativeMessagingEnabled',
        'Set-EdgePolicyNativeMessagingHosts',
        'Set-EdgePolicyCloudPrintEnabled',
        'Set-EdgePolicyCloudPrintURL',
        'Set-EdgePolicyPasswordProtectionAllowed',
        'Set-EdgePolicyRelatedWebsiteSetsEnabled',
        'Set-EdgePolicyRelatedWebsiteSets',
        'Set-EdgePolicyEdgeExperimentsEnabled',
        'Set-EdgePolicyEdgeExperimentsGroups',
        'Set-EdgePolicyEdgeWorkspacesEnabled',
        'Set-EdgePolicyEdgeWorkspaces'
    )
    CmdletsToExport = @()
    VariablesToExport = @()
    AliasesToExport = @()
}
